### ISSUE TITLE
Ortholinear keyboard compatibility question

### ISSUE THREAD

**Issue by geoah** [tin-cat/dec-mini#1]
Hey there, love the dec-mini idea, thank you for making and sharing it.

I've started printing the various parts and ordered most of the hardware so hopefully I should start sanding soon enough, but I wanted to ask about the keyboard compatibility.

Your renders are showing an ortholinear keyboard instead of the DREVO one that is suggested in the docs, so I wanted to ask if you've actually found a compatible ortho PCB that might actually fit. I assume that it mostly for easy of making the 3D model for the renders but wanted to ask and make sure as ideally I'd like an ortholinear keyboard for my mini :D

Thank you for all your hard work!

**Comment by tin-cat** [comment]
Hi Geoah, so glad you like the project! Would love to see your build! :)

You're right, the ortholinear keyboard on the renders is just a simplification, the actual keyboard has the layout of the Drevo Calibur V2. I would say other keyboard of the same size would fit well on the DEC Mini, but the screws layout on the DEC Mini are placed exactly for the Drevo Calibur V2, and I cannot confirm this screw layout is a standard used in other keyboards too.

There's a guide here where you'll find the exact sizes and placement of the screws on the DEC Mini: https://decmini.com/build/compatible-keyboards/

In any case, as long as your keyboard's width/height fits into the DEC Mini's, it shouldn't be too difficult to make it stand at the right height with some hacking of the original 3D files and maybe the 3d-printing of additional supports for your specific keyboard. If that's the case, it'll be nice if you share them so I'll include your modifications on the site!

Thanks!
